import type { Metadata } from "next";
import Link from "next/link";
import {
  ArrowRight,
  Check,
  X,
  Laptop,
  Sparkles,
  ShieldCheck,
  Zap,
  BookOpen,
  Download,
  RotateCcw,
  CheckCircle2,
} from "lucide-react";
import type { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Vellum for Windows & PC Alternative — Typeset Books in the Cloud | Racana",
  description:
    "Looking for Vellum on Windows? Vellum is Mac-only and costs $249.99. Racana is the modern, cloud-native book publisher for Windows, Linux & Mac. Bookstore-grade interior PDF + EPUB 3 in minutes for $29.",
  alternates: { canonical: "/vellum-alternative-windows" },
  openGraph: {
    title: "The Cloud-Native Vellum for Windows, Linux & Mac — Racana",
    description:
      "Format print-ready paperbacks and Kindle EPUBs on your Windows PC without buying a Mac or renting cloud virtual machines. Typeset in minutes with automated Amazon KDP gutter checks.",
    type: "article",
    url: "/vellum-alternative-windows",
  },
  keywords: [
    "Vellum for Windows",
    "Vellum alternative PC",
    "book formatting software Windows",
    "Vellum Mac alternative",
    "KDP book formatting Windows",
    "typesetting software for PC",
    "InDesign alternative for authors",
    "cloud book typesetting",
  ],
};

const comparisonFeatures = [
  {
    feature: "Supported Operating Systems",
    racana: "Windows 11/10, Linux, ChromeOS, macOS (Any modern browser)",
    vellum: "macOS only (Mac hardware strictly required)",
    indesign: "Windows & macOS (Heavy desktop installation)",
    highlight: true,
  },
  {
    feature: "Upfront Cost & Licensing",
    racana: "Free Preview · $29 (₹2,450) flat per book (No subscription)",
    vellum: "$199.99 (eBooks only) or $249.99 (Paperback + eBook)",
    indesign: "$59.99/month ($719/year Adobe Creative Cloud)",
    highlight: true,
  },
  {
    feature: "Hardware Requirements",
    racana: "None (Zero installation, runs in the cloud)",
    vellum: "Must own or rent a physical Apple Mac computer",
    indesign: "High-spec PC with dedicated RAM & GPU",
    highlight: false,
  },
  {
    feature: "Typesetting Engine",
    racana: "Native Typst (Mathematical micro-typography & optical kerning)",
    vellum: "WebKit-based HTML/CSS rendering",
    indesign: "Adobe PostScript / InDesign composition engine",
    highlight: false,
  },
  {
    feature: "Amazon KDP & IngramSpark Margin QA",
    racana: "Automated 10-point print QA + Formatting Refund Guarantee",
    vellum: "Preset margins (Limited custom binding adjustments)",
    indesign: "100% manual calculation and ruler alignment",
    highlight: true,
  },
  {
    feature: "Indian & Multi-Script Typography",
    racana: "Built-in support for Devanagari, Tamil, Malayalam & Latin",
    vellum: "Latin-alphabet focused (Known Indic rendering issues)",
    indesign: "Requires World-Ready Composer configuration",
    highlight: true,
  },
  {
    feature: "30-Day Free Typo Re-generation",
    racana: "Included free (Re-upload revised manuscript for 30 days)",
    vellum: "Supported locally (if you still have the Mac)",
    indesign: "Manual text replacement & reflow checks",
    highlight: false,
  },
  {
    feature: "Learning Curve",
    racana: "Minutes (Upload DOCX → Pick style → Download PDF)",
    vellum: "1–2 hours",
    indesign: "20–40 hours of professional training",
    highlight: false,
  },
  {
    feature: "Turnaround Time",
    racana: "Under 120 seconds",
    vellum: "Manual project setup & chapter styling",
    indesign: "Days to weeks of manual typesetting",
    highlight: false,
  },
];

const faqs: [string, string][] = [
  [
    "Is there an official version of Vellum for Windows?",
    "No. 168 Software (the creators of Vellum) have explicitly stated that Vellum is built exclusively for macOS and there are no plans to develop a Windows version. For years, Windows authors had to either purchase expensive Mac hardware, run slow 'Mac in the Cloud' virtual machines, or hire freelancers.",
  ],
  [
    "How does Racana work on Windows without installing anything?",
    "Racana is 100% cloud-native. You open Racana in Google Chrome, Microsoft Edge, Firefox, or Brave on your Windows 10 or 11 PC, upload your Microsoft Word (.docx) manuscript, and our cloud-based Typst typesetting engine compiles your book interior into a print-ready PDF and validated EPUB 3.0 file in seconds.",
  ],
  [
    "Will Amazon KDP and IngramSpark accept PDF files generated by Racana on Windows?",
    "Yes, with a 100% money-back guarantee. Racana automatically applies binding-aware gutters (preventing text from falling into the spine), embeds all vector fonts, ensures compliant bleed margins, and validates page counts against Amazon KDP and IngramSpark technical specifications.",
  ],
  [
    "What manuscript formats can I upload from my PC?",
    "Racana accepts standard Microsoft Word (.docx) files as well as raw .pdf documents. DOCX is recommended as Racana automatically detects chapter headings, sub-headings, frontmatter (title page, copyright, dedication, contents), and backmatter without manual tagging.",
  ],
  [
    "Can I generate both paperback interiors and Kindle EPUBs?",
    "Yes. With a single upload, Racana generates your print-ready PDF interior (in standard 5x8, 5.5x8.5, 6x9, or 8.5x11 trim sizes) as well as an EPUB 3.0 digital eBook package compatible with Kindle Paperwhite, Kobo, and Apple Books.",
  ],
  [
    "What if I find a typo after downloading my book on Windows?",
    "Racana includes a 30-Day Free Revision Grace Period. You can fix the typo in Word on your PC, re-upload the revised file, and re-generate your print-ready PDF and EPUB at zero additional charge.",
  ],
];

function SectionLabel({ label }: { label: string }) {
  return (
    <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-[#A34825]/10 text-[#A34825] text-xs font-semibold uppercase tracking-wider mb-4">
      <Sparkles className="w-3.5 h-3.5" />
      <span>{label}</span>
    </div>
  );
}

export default function VellumAlternativeWindowsPage() {
  return (
    <main className="min-h-screen bg-[#FAF8F5] text-[#1C1917] selection:bg-[#A34825] selection:text-white">
      {/* Navigation Bar */}
      <nav className="border-b border-[#E8E2D5] bg-[#FAF8F5]/90 backdrop-blur-md sticky top-0 z-50 px-5 md:px-12 py-4">
        <div className="mx-auto max-w-6xl flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <span className="font-serif text-2xl font-bold tracking-wider text-[#1C1917]">RACANA</span>
            <span className="text-[10px] font-mono uppercase px-2 py-0.5 rounded-md bg-[#F4EFEA] text-[#A34825] border border-[#E8E2D5]">
              Cloud Studio
            </span>
          </Link>
          <div className="flex items-center gap-4">
            <Link
              href="/"
              className="text-xs font-medium text-[#78716C] hover:text-[#1C1917] transition-colors hidden sm:inline"
            >
              Overview
            </Link>
            <Link
              href="/upload"
              className="px-4 py-2 rounded-xl bg-[#1C1917] hover:bg-[#2E2824] text-white text-xs font-semibold shadow-xs transition-all flex items-center gap-1.5"
            >
              <span>Format Manuscript Free</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="pt-20 pb-16 px-5 md:px-12 lg:px-16 border-b border-[#E8E2D5]">
        <div className="mx-auto max-w-4xl text-center">
          <SectionLabel label="No Mac Required · 100% Cloud-Native" />
          <h1 className="font-serif text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-[#1C1917] leading-[1.15]">
            The Cloud-Native Vellum for Windows, Linux &amp; Mac.
          </h1>
          <p className="mt-6 text-base sm:text-lg text-[#78716C] max-w-2xl mx-auto leading-relaxed">
            Vellum produces beautiful books, but locks you into a $1,000+ Mac and a $249.99 software license.
            Racana brings bookstore-grade automated interior typography, KDP-certified gutters, and instant Kindle EPUBs to any PC browser for $29 flat.
          </p>

          <div className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link
              href="/upload"
              className="w-full sm:w-auto px-8 py-4 rounded-xl bg-[#A34825] hover:bg-[#8C3C1F] text-white text-sm font-semibold shadow-lg hover:shadow-xl transition-all flex items-center justify-center gap-2"
            >
              <Laptop className="w-4 h-4" />
              <span>Format Your Book on Windows — $0 Preview</span>
            </Link>
            <Link
              href="/#xray"
              className="w-full sm:w-auto px-8 py-4 rounded-xl border border-[#D6CEBE] bg-[#FDFBF7] text-[#1C1917] hover:border-[#1C1917] text-sm font-semibold transition-all flex items-center justify-center gap-2"
            >
              <Zap className="w-4 h-4 text-[#A34825]" />
              <span>Free Manuscript Health X-Ray</span>
            </Link>
          </div>

          <div className="mt-8 flex flex-wrap items-center justify-center gap-6 text-xs text-[#78716C]">
            <span className="flex items-center gap-1.5">
              <Check className="w-4 h-4 text-[#166534]" />
              Works on Windows 11 &amp; 10
            </span>
            <span className="flex items-center gap-1.5">
              <Check className="w-4 h-4 text-[#166534]" />
              Zero installation or virtualization
            </span>
            <span className="flex items-center gap-1.5">
              <Check className="w-4 h-4 text-[#166534]" />
              30-Day Free Typo Re-generation
            </span>
          </div>
        </div>
      </section>

      {/* Comparison Matrix Table */}
      <section className="py-20 px-5 md:px-12 lg:px-16 border-b border-[#E8E2D5] bg-white">
        <div className="mx-auto max-w-5xl">
          <div className="text-center max-w-2xl mx-auto mb-14">
            <SectionLabel label="Head-to-Head Comparison" />
            <h2 className="font-serif text-3xl sm:text-4xl font-bold text-[#1C1917]">
              Racana vs. Vellum vs. Adobe InDesign
            </h2>
            <p className="mt-3 text-sm text-[#78716C]">
              Compare how the industry standards stack up for independent authors publishing on Windows.
            </p>
          </div>

          <div className="overflow-x-auto rounded-2xl border border-[#E8E2D5] shadow-sm">
            <table className="w-full text-left text-xs sm:text-sm border-collapse">
              <thead>
                <tr className="border-b border-[#E8E2D5] bg-[#F8F5EE]">
                  <th className="py-4 px-5 font-semibold text-[#1C1917] w-1/4">Feature</th>
                  <th className="py-4 px-5 font-bold text-[#A34825] bg-[#F4EFEA]/80 w-1/3 border-x border-[#E8E2D5]">
                    Racana (Cloud Studio)
                  </th>
                  <th className="py-4 px-5 font-semibold text-[#78716C] w-1/5">Vellum</th>
                  <th className="py-4 px-5 font-semibold text-[#78716C] w-1/5">Adobe InDesign</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#E8E2D5]">
                {comparisonFeatures.map((row, i) => (
                  <tr
                    key={row.feature}
                    className={row.highlight ? "bg-[#FAF8F5]/80" : i % 2 === 0 ? "bg-white" : "bg-[#FDFBF7]"}
                  >
                    <td className="py-4 px-5 font-semibold text-[#1C1917]">{row.feature}</td>
                    <td className="py-4 px-5 font-medium text-[#1C1917] bg-[#F4EFEA]/40 border-x border-[#E8E2D5]">
                      <div className="flex items-start gap-2">
                        <CheckCircle2 className="w-4 h-4 text-[#166534] shrink-0 mt-0.5" />
                        <span>{row.racana}</span>
                      </div>
                    </td>
                    <td className="py-4 px-5 text-[#78716C]">
                      <div className="flex items-start gap-2">
                        {row.vellum.includes("macOS only") || row.vellum.includes("Must own") ? (
                          <X className="w-4 h-4 text-[#DC2626] shrink-0 mt-0.5" />
                        ) : null}
                        <span>{row.vellum}</span>
                      </div>
                    </td>
                    <td className="py-4 px-5 text-[#78716C]">
                      <div className="flex items-start gap-2">
                        {row.indesign.includes("Adobe Creative Cloud") || row.indesign.includes("20–40 hours") ? (
                          <X className="w-4 h-4 text-[#DC2626] shrink-0 mt-0.5" />
                        ) : null}
                        <span>{row.indesign}</span>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* Why Windows Authors Love Racana */}
      <section className="py-20 px-5 md:px-12 lg:px-16 border-b border-[#E8E2D5] bg-[#FAF8F5]">
        <div className="mx-auto max-w-5xl">
          <div className="text-center max-w-2xl mx-auto mb-14">
            <SectionLabel label="Engineered for Windows Authors" />
            <h2 className="font-serif text-3xl sm:text-4xl font-bold text-[#1C1917]">
              Stop Overpaying for Mac Workarounds
            </h2>
            <p className="mt-3 text-sm text-[#78716C]">
              Until now, PC authors had three bad choices: buy an expensive Mac, rent clunky virtual machines, or hire expensive formatters.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="p-6 rounded-2xl bg-white border border-[#E8E2D5] shadow-xs">
              <div className="w-10 h-10 rounded-xl bg-[#F4EFEA] text-[#A34825] flex items-center justify-center mb-4">
                <Laptop className="w-5 h-5" />
              </div>
              <h3 className="font-serif font-bold text-lg text-[#1C1917] mb-2">
                No "Mac in the Cloud" Virtual Machines
              </h3>
              <p className="text-xs text-[#78716C] leading-relaxed">
                Renting remote Macs costs $25–$45/month with laggy mouse controls and file-transfer hassles. Racana runs natively in your Windows browser with zero latency.
              </p>
            </div>

            <div className="p-6 rounded-2xl bg-white border border-[#E8E2D5] shadow-xs">
              <div className="w-10 h-10 rounded-xl bg-[#F4EFEA] text-[#A34825] flex items-center justify-center mb-4">
                <ShieldCheck className="w-5 h-5" />
              </div>
              <h3 className="font-serif font-bold text-lg text-[#1C1917] mb-2">
                KDP Formatting Refund Guarantee
              </h3>
              <p className="text-xs text-[#78716C] leading-relaxed">
                Every file generated on Windows is checked by our 10-point print QA suite for gutter width, bleed, spine margins, and font embedding. If Amazon rejects your interior for a formatting reason, forward the rejection within 30 days for a full refund.
              </p>
            </div>

            <div className="p-6 rounded-2xl bg-white border border-[#E8E2D5] shadow-xs">
              <div className="w-10 h-10 rounded-xl bg-[#F4EFEA] text-[#A34825] flex items-center justify-center mb-4">
                <RotateCcw className="w-5 h-5" />
              </div>
              <h3 className="font-serif font-bold text-lg text-[#1C1917] mb-2">
                30-Day Free Typo Re-generation
              </h3>
              <p className="text-xs text-[#78716C] leading-relaxed">
                Spotted a typo in your printed proof copy? Unlike freelance designers who charge hourly for revisions, Racana lets you re-upload and re-generate your book completely free for 30 days.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* 3 Steps on Windows */}
      <section className="py-20 px-5 md:px-12 lg:px-16 border-b border-[#E8E2D5] bg-white">
        <div className="mx-auto max-w-4xl">
          <div className="text-center max-w-2xl mx-auto mb-14">
            <SectionLabel label="Simple 2-Minute Workflow" />
            <h2 className="font-serif text-3xl sm:text-4xl font-bold text-[#1C1917]">
              From Word .docx to Print-Ready Book on PC
            </h2>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-8">
            <div className="text-center">
              <span className="w-12 h-12 rounded-2xl bg-[#1C1917] text-[#F8F5EE] font-serif font-bold text-lg flex items-center justify-center mx-auto mb-4">
                1
              </span>
              <h3 className="font-semibold text-base text-[#1C1917] mb-1">Upload DOCX from PC</h3>
              <p className="text-xs text-[#78716C] leading-relaxed">
                Drop your finished Word manuscript. Racana auto-detects titles, chapters, frontmatter, and verse.
              </p>
            </div>

            <div className="text-center">
              <span className="w-12 h-12 rounded-2xl bg-[#A34825] text-white font-serif font-bold text-lg flex items-center justify-center mx-auto mb-4">
                2
              </span>
              <h3 className="font-semibold text-base text-[#1C1917] mb-1">Pick Style &amp; Trim</h3>
              <p className="text-xs text-[#78716C] leading-relaxed">
                Choose classic or modern typography and your target trim size (5×8″, 5.5×8.5″, 6×9″, 8.5×11″).
              </p>
            </div>

            <div className="text-center">
              <span className="w-12 h-12 rounded-2xl bg-[#1C1917] text-[#F8F5EE] font-serif font-bold text-lg flex items-center justify-center mx-auto mb-4">
                3
              </span>
              <h3 className="font-semibold text-base text-[#1C1917] mb-1">Download PDF &amp; EPUB</h3>
              <p className="text-xs text-[#78716C] leading-relaxed">
                Inspect in 3D, download your print-ready PDF and Kindle EPUB, and upload directly to Amazon KDP.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-20 px-5 md:px-12 lg:px-16 border-b border-[#E8E2D5] bg-[#FAF8F5]">
        <div className="mx-auto max-w-4xl">
          <div className="text-center max-w-2xl mx-auto mb-14">
            <SectionLabel label="Frequently Asked Questions" />
            <h2 className="font-serif text-3xl sm:text-4xl font-bold text-[#1C1917]">
              Publishing on Windows with Racana
            </h2>
          </div>

          <div className="space-y-4">
            {faqs.map(([q, a]) => (
              <div key={q} className="p-6 rounded-2xl bg-white border border-[#E8E2D5] shadow-xs">
                <h3 className="font-semibold text-sm sm:text-base text-[#1C1917] mb-2">{q}</h3>
                <p className="text-xs sm:text-sm text-[#78716C] leading-relaxed">{a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Final CTA Banner */}
      <section className="py-20 px-5 md:px-12 text-center bg-[#1C1917] text-[#F8F5EE]">
        <div className="mx-auto max-w-3xl">
          <h2 className="font-serif text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight mb-4">
            Ready to Format Your Book on Windows?
          </h2>
          <p className="text-sm sm:text-base text-[#A8A29E] max-w-xl mx-auto mb-8 leading-relaxed">
            Upload your manuscript today. Inspect your free watermarked interior preview and 3D book mockup before paying a single cent.
          </p>
          <Link
            href="/upload"
            className="inline-flex items-center justify-center gap-2 px-8 py-4 rounded-xl bg-[#A34825] hover:bg-[#8C3C1F] text-white text-sm font-semibold shadow-lg hover:shadow-xl transition-all"
          >
            <span>Start Typesetting on PC — Free Preview</span>
            <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </section>

      {/* JSON-LD Structured Data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "SoftwareApplication",
            name: "Racana — Vellum Alternative for Windows",
            operatingSystem: "Windows, Linux, macOS, ChromeOS",
            applicationCategory: "DesignApplication",
            offers: {
              "@type": "Offer",
              price: "29.00",
              priceCurrency: "USD",
            },
            description:
              "The cloud-native Vellum alternative for Windows. Typeset print-ready book interior PDFs and Kindle EPUBs in minutes without a Mac.",
          }),
        }}
      />
    </main>
  );
}
